Roman_Chulyukin_Task_1_Junior
Xekra/In-memory-Redis-cache pull request #1
Opened 2022-03-12 12:54 UTC by Xekra

Честно сказать, мне кажется, что на этот проект без слез не взглянешь 😞 
Я честно старался, но в процессе какая-то каша в голове образовалась.

2022-03-15 09:52 UTC, UNiqkue commented on mvnw.cmd
> +cmd /C exit /B %ERROR_CODE%
как мне кажется, что файлы mvnw, mvnw.cmd не нужны, так как достаточно стандартных команд mvn для проекта (возможно я неправ, так как в проектах не использовал mvnw и mvnw.cmd). И их можно спокойно в .gitgnore файл записывать вместе с папкой .mvn. Локально развернул проект у себя и запустилось без них

2022-03-15 09:52 UTC, UNiqkue commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
как вариант указать название проекта в artifactId и версию новую без снэпшота (но это всё тоже некритично)

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/ImplementationRedisApplication.java
> +package com.chulyukin.Roman_Chulyukin_Task_1_Junior;
обычно как по себе заметил, что после 2-ой точки можно общее название проекта прописать, тот же implementation_redis, так как Roman_Chulyukin_Task_1_Junior в названии пакета очень громоздкое и не отражает суть проекта. 

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +                System.out.println("Select method  " + op.getCommandName() + " " + op.getCacheObject().getKey()
как вариант настроить логирование вместо sout. Но я его также не настраивал)))

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/dialect/MyDialect.java
> +    MyService myService;
поле private

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/dialect/MyDialect.java
> +
как вариант ещё можно автоварить через конструктор и бывает достаточно удобным  

описано тут https://habr.com/ru/post/472994/

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/service/MyService.java
> +@Service
не вижу смысла создавать бин от интерфейса. Тем более в имлементации тот же @Service над MyServiceImpl уже объявлен

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +        return ResponseEntity.badRequest().build();
если я правильно понимаю, то после каждого POST запроса, даже если он прошёл успешно, будет возвращаться код 400 (BAD_REQUEST). В случае успеха должен возвращаться код 200 ResponseEntity.ok()

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/repository/MapCache.java
> +    }
в случае хранилища было бы неплохо использовать паттерн Singleton, так как будет гарантировать, что такое хранилище одно.
https://refactoring.guru/ru/design-patterns/singleton
Тут разбирают плюсы минусы реализаций https://habr.com/ru/post/129494/

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +    MyDialect myDialect;
private

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +            if (op.getCommandName().equalsIgnoreCase("DELETE")) {
как неплохой вариант для каждой команды сделать свой метод и запрос, например для команды delete
@DeleteMapping("/operation/{operationId}") и т.д.

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +            if (op.getCommandName().equalsIgnoreCase("DELETE")) {
и как правило методы контроллера должны быть небольшими, и выполнять только приёмку, возврат сущностей и маппинг. Всю остальную бизнес-логику лучше перенести в сервис

2022-03-15 09:52 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/repository/MapCache.java
> +    private final Map<String, Object> cache = new HashMap<>();
по поводу redis можно прочитать их туториал https://www.baeldung.com/spring-data-redis-tutorial#conclusion и там же есть ссылка на примерный код

2022-03-16 15:43 UTC, AndryLat requested changes

2022-03-16 15:43 UTC, AndryLat commented on HELP.md
> +# Getting Started
Зачем этот документ тут? какую полезную нагрузку в контексте проекта он несет ?

2022-03-16 15:43 UTC, AndryLat commented on README.md
> +- Operation содержит описание объекта, который передается post методом серверу.
Классы лучше указывать полностью, с пакетом, так их легче искать в ИДЕ

2022-03-16 15:43 UTC, AndryLat commented on Redis Implementaiton.postman_collection.json
> +{
Хорошая идея положить коллекцию постмена:)

2022-03-16 15:43 UTC, AndryLat commented on mvnw.cmd
> +cmd /C exit /B %ERROR_CODE%
А что, если нет мавена локально?:) Тут все верно.

2022-03-16 15:43 UTC, AndryLat commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Как раз лучше указывать снапшот, чтобы в зависимостях подхватывалась последняя версия кода всегда.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/ImplementationRedisApplication.java
> +package com.chulyukin.Roman_Chulyukin_Task_1_Junior;
Поддерживаю, пакеты мы так не именуем, особенно не используем заглавные буквы.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/ImplementationRedisApplication.java
> +package com.chulyukin.Roman_Chulyukin_Task_1_Junior;
Можно сделат ьпакеты так: com.chulyukin.yourcodereview.testtask1

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +                System.out.println("Select method  " + op.getCommandName() + " " + op.getCacheObject().getKey()
У вас серверное приложение, sout это самое некрасивое решение, что можно придумать.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +    public ResponseEntity<Void> determineParametrs(@RequestBody List<Operation> operation) {
Всегда пользователю лучше что-то вернуть

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +        for (Operation op: operation) {
о чем говорит имя op?

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +    public ResponseEntity<Void> determineParametrs(@RequestBody List<Operation> operation) {
Почему у нас список, а называется "операция"?

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +            if (op.getCommandName().equalsIgnoreCase("KEYS")) {
Строки правильнее сравнивать от констант к тому, чт оможет быть нал, а не наоборот. то есть "KEYS".equals () никогда не упадет с NPE,а твой вариант может.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +        /*if (operation.getCommandName().equalsIgnoreCase("SET")) {
Неиспользуемый код - удаляем. Эт омусор, который затрудняет чтение класса и врядли когда-то пригодится.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +    public Map<String, Object>  methodGETAll() {
Абревиатуры и т.д. всегда пишем, что первая буква с большой, остальные в маленькой.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +    public String methodSET(CacheObject cacheObject) {
Вся эта логика должна быть в сервисе. И там же должны быть влаидации.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +            if (op.getCommandName().equalsIgnoreCase("GET")) {
названия операций нужно вынести в константы.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/dialect/MyDialect.java
> +
В целом лучше всегда через конструктор инициализировать.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/dialect/MyDialect.java
> +public class MyDialect {
Не понимаю предназначения этого класса.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/entitys/CacheObject.java
> +* Создал класс, чтобы хранить пару ключ значение
Учитесь оформлять полноценные джава доки. Это бесполезный комментарий.

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/entitys/Operation.java
> +public class Operation {
Можно было добавить request чтобы показать, что это pojo для десериализации джейсона

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/entitys/Operation.java
> +package com.chulyukin.Roman_Chulyukin_Task_1_Junior.entitys;
entitys - явно не так пишется:)

2022-03-16 15:43 UTC, AndryLat commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/entitys/Operation.java
> +    private String commandName;
можно просто name

2022-03-16 22:56 UTC, UNiqkue commented on mvnw.cmd
> +cmd /C exit /B %ERROR_CODE%
да, я прочитал о том, что для этого используется, ну тут кому как удобно)

2022-03-16 22:57 UTC, UNiqkue commented on src/main/java/com/chulyukin/Roman_Chulyukin_Task_1_Junior/controller/MyController.java
> +                System.out.println("Select method  " + op.getCommandName() + " " + op.getCacheObject().getKey()
@Xekra настроил у себя логирование)

2023-04-08 15:03 UTC, closed without merging